version: "3.9"
services:
    ######################################################
    ## Adminer ###########################################
    ## PORT: 8080 ########################################
    ######################################################
    adminer:
<<<<<<< Updated upstream
        container_name: ${APP_PREFIX}adminer
=======
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}adminer
>>>>>>> Stashed changes
        image: adminer
        restart: always
        volumes:
            - ${ADMINER_CSS_PATH}:/var/www/html/adminer.css