version: "3.9"
services:
    ######################################################
    ## Adminer ###########################################
    ## PORT: 8080 ########################################
    ######################################################
    adminer:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}adminer
        image: adminer
        restart: always
        volumes:
          - ${ADMINER_CSS_PATH:-${MOUNT_BASE_PATH:-./}adminer}/adminer.css:/var/www/html/adminer.css
