version: "3.9"
services:
    ######################################################
    ## Adminer ###########################################
    ## PORT: 8080 ########################################
    ######################################################
    adminer:
        container_name: ${APP_PREFIX}adminer
        image: adminer
        restart: always
        volumes:
            - ${ADMINER_CSS_PATH}:/var/www/html/adminer.css