version: "3.9"
services:
    ######################################################
    ## COMEDIAN ##########################################
    ## PORT: 8080 ########################################
    ######################################################
    comedian:
        image: maddevsio/comedian
        restart: on-failure
        environment:
            TZ: Asia/Hong_Kong
            # DATABASE: comedian:comedian@tcp(db:3306)/comedian?parseTime=true
            HTTP_BIND_ADDR: 0.0.0.0:8080
            SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
            SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
            SLACK_VERIFICATION_TOKEN: ${SLACK_VERIFICATION_TOKEN}
