---
version: '3'
services:

  #########################################################
  ## FreqTrade ############################################
  ## Ports: 8080 ##########################################
  #########################################################
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: ${APP_PREFIX:-default-}freqtrade
    volumes:
      - freqtrade-data:/freqtrade/user_data
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy SampleStrategy
    networks:
      - env-network

volumes:
    freqtrade-data:
        driver: local

networks:
    env-network:
        name: ${NETWORK_NAME:-default_network}
        external: true




# APP_NAME=home
# APP_PREFIX=${APP_NAME}-
# NETWORK_NAME=home
# BASE_PATH=./
# MOUNT_BASE_PATH=${BASE_PATH}/docker/mnt
# BUILD_BASE_PATH=${BASE_PATH}/docker/docker-build-library
# COMPOSE_BASE_PATH=/compose
# NETWORK_BASE_FILE=${COMPOSE_BASE_PATH}/network.yml
# DOCKER_SOCK_PATH=/var/run/docker.sock
# DOCKER_LIB_PATH=/var/lib/docker
# TZ=Asia/Hong_Kong