services:
    ######################################################
    ## Infisical db-migration ############################
    ######################################################
    db-migration:
        container_name: infisical-db-migration
        image: infisical/infisical:${INFISICAL_IMAGE_TAG:-latest-postgres}
        command: npm run migration:latest
        pull_policy: always
        environment:
            - NODE_ENV=production
            - DB_CONNECTION_URI=${INFISICAL_DB_CONNECTION_URI:-postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${APP_PREFIX:-default-}postgres:5432/${POSTGRES_DB:-postgres}}
            - REDIS_URL=redis://${APP_PREFIX:-default-}redis:6379
        networks:
            - secret

    ######################################################
    ## Infisical #########################################
    ## Port: 8080 ########################################
    ######################################################
    infisical:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}infisical
        restart: unless-stopped
        image: infisical/infisical:${INFISICAL_IMAGE_TAG:-latest-postgres}
        environment:
            - NODE_ENV=production
            - DB_CONNECTION_URI=${INFISICAL_DB_CONNECTION_URI:-postgres://${INFISICAL_POSTGRES_USER:-postgres}:${INFISICAL_POSTGRES_PASSWORD:-postgres}@${APP_PREFIX:-default-}postgres:5432/${INFISICAL_POSTGRES_DB:-postgres}}
            - REDIS_URL=${INFISICAL_REDIS_URL:-redis://${APP_PREFIX:-default-}redis:6379}
            - AUTH_SECRET=${INFISICAL_AUTH_SECRET:-${AUTH_SECRET:-ea41f2b93b94e929c4686314d0ee5e493625861105f21fbe352a2b44857ffe5b}}
            - ENCRYPTION_KEY=${INFISICAL_ENCRYPTION_KEY:-${ENCRYPTION_KEY:-NYkBpn84fRg7Pf3VFpYrVrTXFrnpBSrb}}
            - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
            - SMTP_PORT=${SMTP_PORT:-587}
            - SMTP_USERNAME=${SMTP_USERNAME:-}
            - SMTP_PASSWORD=${SMTP_PASSWORD:-}
            - SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS:-}
            - SMTP_FROM_NAME=${SMTP_FROM_NAME:-}
        #networks:
          #- ext-network
          
    ######################################################
    ## Infisical CLI #####################################
    ######################################################
    infisical-cli:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}infisical-cli
        image: infisical/infisical-cli:latest
        
