version: "3.9"
services:
    ######################################################
    ## Invoice Plane #####################################
    ######################################################
    invoiceplane:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}invoiceplane
        image: mhzawadi/invoiceplane:dev
        volumes:
            - ${INVOICEPLANE_DATA:-invoiceplane_data}:/var/www/html/uploads
        environment:
            - TZ=${TZ:-utc}
            - MYSQL_HOST=${MYSQL_HOST:-mariadb_10_4}
            - MYSQL_USER=${MYSQL_USER:-${MYSQL_USERNAME:-user}}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
            - MYSQL_DB=${MYSQL_DATABASE:-default}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
            - IP_URL=${INVOICEPLANE_URL:-http://invoiceplane.docker.local}
            - DISABLE_SETUP=false
volumes:
    invoiceplane_data:
        driver: local
