version: "3.9"
services:
    ######################################################
    ## Maddy #############################################
    ## PORT: 25, 143, 587, 993 ###########################
    ######################################################
    maddy:
<<<<<<< Updated upstream
        container_name: ${APP_PREFIX}maddy
=======
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}maddy
>>>>>>> Stashed changes
        image: foxcpp/maddy
        # image: foxcpp/maddy:0.6
        environment:
            - MADDY_HOSTNAME=${MADDY_HOSTNAME:-mx.maddy.test}
            - MADDY_DOMAIN=${MADDY_DOMAIN:-maddy.test}
        volumes:
            - maddy_data:/data

volumes:
    maddy_data:
        driver: local