version: "3.9"
services:
    ######################################################
    ## Mongo #############################################
    ## PORT: 27017 #######################################
    ######################################################
    mongo:
<<<<<<< Updated upstream
        container_name: ${APP_PREFIX}mongo
=======
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}mongo
>>>>>>> Stashed changes
        image: ${MONGO_IMAGE:-mongo}
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
        driver: local
