version: "3.9"
services:
    ######################################################
    ### MYSQL ############################################
    ## PORT: 3306 ########################################
    ######################################################
    mysql:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}mysql
        image: ${MYSQL_IMAGE:-mysql}
        restart: always
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE:-default}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_USER=${MYSQL_USER:-${MYSQL_USERNAME:-user}}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
        volumes:
            - mysql_data:/var/lib/mysql
            - mysql_config:/etc/mysql

volumes:
    mysql_data:
        driver: local
    mysql_config:
        driver: local
