services:
    #########################################################
    ## N8N ##################################################
    ## Port: 5678 ###########################################
    #########################################################
    n8n:
        container_name: ${APP_PREFIX:-${APP_NAME:-default}-}n8n
        image: n8nio/n8n
        restart: always
        #ports:
          #- "5678:5678"
        environment:
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:-true}
            - N8N_HOST=${N8N_HOST:-localhost}
            - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
            - NODE_ENV=${N8N_ENV:-production}
            - N8N_SMTP_HOST=${N8N_SMTP_HOST}
            - N8N_SMTP_PORT=${N8N_SMTP_PORT}
            - N8N_SMTP_SENDER=${N8N_SMTP_SENDER}
        volumes:
            - n8n-data:/home/node/.n8n

volumes:
  n8n-data:
