version: "3.9"
services:
    ############################################
    ### POSTGRES ###############################
    ### PORT: 5432 #############################
    ############################################
    postgres:
        container_name: ${APP_PREFIX:-${APP_NAME}_}postgres
        image: postgres:${POSTGRES_VERSION:-latest}
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres} 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password} 
            - POSTGRES_DB=${POSTGRES_DATABASE:-default} 
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
