version: "3.9"
services:
    ############################################
    ### POSTGRES ###############################
    ### PORT: 5432 #############################
    ############################################
    postgres:
        container_name: ${APP_PREFIX:-${APP_NAME}_}postgres
        image: postgres:${POSTGRES_VERSION:-latest}
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres} # The PostgreSQL user (useful to connect to the database)
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password} # The PostgreSQL password (useful to connect to the database)
            - POSTGRES_DB=${POSTGRES_DATABASE:-coder} # The PostgreSQL default database (automatically created at first launch)
        volumes:
            - postgres_data:/var/lib/postgresql/data # Use "docker volume rm coder_coder_data" to reset Coder

volumes:
    postgres_data:
