version: "3.9"
services:
    ######################################################
    ## Nginx Proxy Manager ###############################
    ######################################################
    nginx:
        extends:
            file: ${COMPOSE_BASE_PATH}/nginx.yml
            service: nginx-proxy-manager
        container_name: nginx

    ######################################################
    ## MySQL DB ##########################################
    ######################################################
    mysql:
        extends:
            file: ${COMPOSE_BASE_PATH}/mysql.yml
            service: mysql

    ######################################################
    ## Grafana ###########################################
    ######################################################
    grafana:
        extends:
            file: ${COMPOSE_BASE_PATH}/grafana.yml
            service: grafana

    ######################################################
    ## Loki ##############################################
    ######################################################
    loki:
        extends:
            file: ${COMPOSE_BASE_PATH}/loki.yml
            service: loki

    ######################################################
    ## Promtail ##########################################
    ######################################################
    promtail:
        extends:
            file: ${COMPOSE_BASE_PATH}/promtail.yml
            service: promtail

    ######################################################
    ## Code Server #######################################
    ######################################################
    codeserver:
        extends:
            file: ${COMPOSE_BASE_PATH}/codeserver.yml
            service: codeserver

    ######################################################
    ## Adminer ###########################################
    ######################################################
    adminer:
        extends:
            file: ${COMPOSE_BASE_PATH}/adminer.yml
            service: adminer

    ######################################################
    ## Flame #############################################
    ######################################################
    flame:
        extends:
            file: ${COMPOSE_BASE_PATH}/flame.yml
            service: flame

networks:
    env-network:
        name: ${NETWORK_NAME}
        external: true
